eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
server:
  port: 8762
spring:
  application:
    name: cloud-service-member
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
